required = [
  "github.com/elazarl/go-bindata-assetfs"
  "github.com/gogo/protobuf"
  "github.com/golang/protobuf/protoc-gen-go"
  "github.com/jteeuwen/go-bindata"
  "github.com/mwitkow/go-proto-validators"
  "github.com/rakyll/statik"
]

[prune]
  go-tests = true
  # unused-packages = true

# Constrained versions that are defined in WORKSPACE are at the top

[[constraint]]
  # version = "v2.6.0-rc.1-209-gedc3ab29"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
  name = "github.com/docker/distribution"

[[constraint]]
  # version = "docs-v1.12.0-rc4-2016-07-15-7401-g4f3616fb1"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"
  name = "github.com/docker/docker"

[[constraint]]
  # version = "v0.3.0"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"
  name = "github.com/docker/go-connections"

[[constraint]]
  # version = "v0.3.1-11-g9e638d3"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
  name = "github.com/docker/go-units"

[[constraint]]
  # version = "v0.8.0-dev.2-910-gba46b928"
  revision = "ba46b928444931e6865d8618dc03622cac79aa6f"
  name = "github.com/docker/libnetwork"

[[constraint]]
  revision = "9cbd2a1374f46905c68a4eb3694a130610adc62a"
  name = "github.com/docker/libtrust"

[[constraint]]
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
  name = "github.com/docker/spdystream"

[[constraint]]
  # version = "v1.0.0"
  revision = "08a7655d27152912db7aaf4f983275eaf8d128ef"
  name = "github.com/gogo/googleapis"

[[constraint]]
  # version = "v0.4-3-gc0656edd"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
  name = "github.com/gogo/protobuf"

[[constraint]]
  # version = "1.3.0"
  revision = "8cc3a55af3bcf171a1c23a90c4df9cf591706104"
  name = "github.com/grpc-ecosystem/grpc-gateway"

[[constraint]]
  revision = "a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb"
  name = "github.com/opencontainers/go-digest"

[[constraint]]
  revision = "fbd4f31c568b767447302e08fb3531b33bcbf837"
  name = "github.com/openshift/imagebuilder"

[[constraint]]
  revision = "ac6dc9858fa90b751686436fea9a951f183c79bb"
  name = "github.com/openshift/source-to-image"

[[constraint]]
  # version = "v0.8.0-83-ge7e9030" // kubernetes
  revision = "e7e903064f5e9eb5da98208bae10b475d4db0f8c"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  revision = "f7603f4e1c90a14f48a7170db2d625c5ce04db6b"
  name = "github.com/soheilhy/cmux"

[[constraint]]
  revision = "0e1a0aad2f7404e9ad14018b02315af5c2f12ffb"
  name = "github.com/xanzy/go-gitlab"

[[constraint]]
  revision = "de0752318171da717af4ce24d0a2e8626afaeb11"
  name = "golang.org/x/crypto"

[[constraint]]
  # revision = "640f4622ab692b87c2f3a94265e6f579fe38263d" // grpc-gateway
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
  name = "golang.org/x/net"

[[constraint]]
  revision = "95c6576299259db960f6c5b9b69ea52422860fce"
  name = "golang.org/x/sys"

[[constraint]]
  # mirror https://github.com/google/go-genproto
  # revision = "383e8b2c3b9e36c4076b235b32537292176bae20" // grpc-gateway
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"
  name = "google.golang.org/genproto"

[[constraint]]
  # mirror https://github.com/src-d/go-git
  # version = "v4.7.0"
  revision = "d3cec13ac0b195bfb897ed038a08b5130ab9969e"
  name = "gopkg.in/src-d/go-git.v4"

[[constraint]]
  revision = "012f271b5d41baad56190c5f1ae19bff16df0fd8"
  name = "k8s.io/api"

[[constraint]]
  revision = "0dbe21f815eb26c3e48873dbc609191001553a3c"
  name = "k8s.io/apimachinery"

[[constraint]]
  revision = "a4df698a96cf14cb8783233b5b95635e2edf002e"
  name = "k8s.io/kubernetes"

[[constraint]]
  revision = "66066c83e385e385ccc3c964b44fd7dcd413d0ed"
  name = "k8s.io/utils"

# These versions are constrained transitively by bazelbuild/rules.go

[[constraint]]
  # version = "1.1.0"
  revision = "b4deda0973fb4c70b50d226b1af49f3da59f5265"
  name = "github.com/golang/protobuf"

[[constraint]]
  revision = ""
  name = "golang.org/x/net"

[[constraint]]
  # mirror https://github.com/grpc/grpc-go
  # version = "1.10.3" // grpc-gateway
  # version = "1.7.5" // kubernetes
  revision = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e"
  name = "google.golang.org/grpc"

[[constraint]]
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"
  name = "github.com/golang/glog"

[[override]]
  # revision = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"
  name = "golang.org/x/text"