required = [
  "github.com/elazarl/go-bindata-assetfs"
  "github.com/gogo/protobuf"
  "github.com/golang/protobuf/protoc-gen-go"
  "github.com/jteeuwen/go-bindata"
  "github.com/mwitkow/go-proto-validators"
  "github.com/rakyll/statik"
]

[prune]
  go-tests = true
  # unused-packages = true

# Constrained versions that are defined in WORKSPACE are at the top

# go-git.v4
#[[constraint]]
#  revision = "d14ea06fba99483203c19d92cfcd13ebe73135f4"
#  name = "github.com/jbenet/go-context"

[[constraint]]
  # version = "v2.6.0-rc.1-209-gedc3ab29"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
  name = "github.com/docker/distribution"

[[constraint]]
  # version = "docs-v1.12.0-rc4-2016-07-15-7401-g4f3616fb1"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"
  name = "github.com/docker/docker"

[[constraint]]
  # version = "v0.3.0"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"
  name = "github.com/docker/go-connections"

[[constraint]]
  # version = "v0.3.1-11-g9e638d3"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
  name = "github.com/docker/go-units"

[[constraint]]
  # version = "v0.8.0-dev.2-910-gba46b928"
  revision = "ba46b928444931e6865d8618dc03622cac79aa6f"
  name = "github.com/docker/libnetwork"

[[constraint]]
  revision = "9cbd2a1374f46905c68a4eb3694a130610adc62a"
  name = "github.com/docker/libtrust"

[[constraint]]
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
  name = "github.com/docker/spdystream"

[[constraint]]
  revision = "84db0d02230aa550f3ec148981e4d75cf316e123"
  name = "github.com/emicklei/go-restful"

[[constraint]]
  revision = "5f88b18a7ad3ebfc46eac02c2e0e80f1533ec349"
  name = "github.com/emicklei/go-restful-openapi"

# go-git.v4
#[[constraint]]
#  revision = "bba54c718c4e39e4db35f73e0c660df44a4de4cd"
#  name = "github.com/emirpasic/gods"

# go-openapi/spec
#[[constraint]]
#  revision = "52eb3d4b47c6a51ce2693c8e614a15a07c1af435"
#  name = "github.com/go-openapi/jsonpointer"

# go-openapi/spec
#[[constraint]]
#  revision = "1c6a3fa339f2743b7b0fd2b842fc455eca2fa9eb"
#  name = "github.com/go-openapi/jsonreference"

[[constraint]]
  revision = "f1468acb3b29cdd5c5f6fa29435d2d2d6e6c9ff1"
  name = "github.com/go-openapi/spec"

#[[constraint]]
#  revision = "dd0dad036e67ae93c27dc64337b3f76296f3a5f0"
#  name = "github.com/go-openapi/swag"

[[constraint]]
  # version = "v1.0.0"
  revision = "08a7655d27152912db7aaf4f983275eaf8d128ef"
  name = "github.com/gogo/googleapis"

[[constraint]]
  # version = "v0.4-3-gc0656edd"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
  name = "github.com/gogo/protobuf"

[[constraint]]
  revision = "8c859bce4beadf04ba687d0efef6619ce2abca2a"  
  name = "github.com/google/go-github"

[[constraint]]
  # version = "1.3.0"
  revision = "8cc3a55af3bcf171a1c23a90c4df9cf591706104"
  name = "github.com/grpc-ecosystem/grpc-gateway"

# go-git.v4
#[[constraint]]
#  # version = "0.5"
#  revision = "81db2a75821ed34e682567d48be488a1c3121088"
#  name = "github.com/kevinburke/ssh_config"

# go-openapi/spec
#[[constraint]]
#  revision = "60711f1a8329503b04e1c88535f419d0bb440bff"
#  name = "github.com/mailru/easyjson"

[[constraint]]
  revision = "a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb"
  name = "github.com/opencontainers/go-digest"

[[constraint]]
  revision = "fbd4f31c568b767447302e08fb3531b33bcbf837"
  name = "github.com/openshift/imagebuilder"

[[constraint]]
  revision = "ac6dc9858fa90b751686436fea9a951f183c79bb"
  name = "github.com/openshift/source-to-image"

# kevinburke
#[[constraint]]
#  revision = "de1592c34d9c6055a32fc9ebe2b3ee50ca468ebe"
#  name = "github.com/pelletier/go-buffruneio"

[[constraint]]
  # version = "v0.8.0-83-ge7e9030" // kubernetes
  revision = "e7e903064f5e9eb5da98208bae10b475d4db0f8c"
  name = "github.com/prometheus/client_golang"

# go-git.v4
#[[constraint]]
#  revision = "da645544ed44df016359bd4c0e3dc60ee3a0da43"
#  name = "github.com/sergi/go-diff"

[[constraint]]
  revision = "f7603f4e1c90a14f48a7170db2d625c5ce04db6b"
  name = "github.com/soheilhy/cmux"

# go-git.v4
#[[constraint]]
#  # version = "v1.3.0"
#  revision = "f187355171c936ac84a82793659ebb4936bc1c23"
#  name = "github.com/src-d/gcfg"

[[constraint]]
  revision = "3cd755d6c4753083fdfcd45b71e88100bf8f2057"
  name = "github.com/studio-b12/gowebdav"

[[constraint]]
  revision = "0e1a0aad2f7404e9ad14018b02315af5c2f12ffb"
  name = "github.com/xanzy/go-gitlab"

# go-git.v4
#[[constraint]]
#  # version = "v0.2.0"
#  revision = "640f0ab560aeb89d523bb6ac322b1244d5c3796c"
#  name = "github.com/xanzy/ssh-agent"

[[constraint]]
  revision = "de0752318171da717af4ce24d0a2e8626afaeb11"
  name = "golang.org/x/crypto"

[[constraint]]
  # revision = "640f4622ab692b87c2f3a94265e6f579fe38263d" // grpc-gateway
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
  name = "golang.org/x/net"

[[constraint]]
  revision = "95c6576299259db960f6c5b9b69ea52422860fce"
  name = "golang.org/x/sys"

[[constraint]]
  # mirror https://github.com/google/go-genproto
  # revision = "383e8b2c3b9e36c4076b235b32537292176bae20" // grpc-gateway
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"
  name = "google.golang.org/genproto"

# 
#[[constraint]]
#  revision = ""
#  name = "gopkg.in/inf.v0"

# go-git.v4
#[[constraint]]
#  # version = "v4.2.1"
#  revision = "59952543636f55de3f860b477b615093d5c2c3e4"
#  name = "gopkg.in/src-d/go-billy.v4"

[[constraint]]
  # mirror https://github.com/src-d/go-git
  # version = "v4.7.0"
  revision = "d3cec13ac0b195bfb897ed038a08b5130ab9969e"
  name = "gopkg.in/src-d/go-git.v4"

# go-git.v4
#[[constraint]]
#  # version = "v0.1.2"
#  revision = "ec4a0fea49c7b46c2aeb0b51aac55779c607e52b"
#  name = "gopkg.in/warnings.v0"

# go-openapi/spec
#[[constraint]]
#  revision = ""
#  name = "gopkg.in/yaml.v2"

[[constraint]]
  revision = "012f271b5d41baad56190c5f1ae19bff16df0fd8"
  name = "k8s.io/api"

[[constraint]]
  revision = "0dbe21f815eb26c3e48873dbc609191001553a3c"
  name = "k8s.io/apimachinery"

[[constraint]]
  revision = "a4df698a96cf14cb8783233b5b95635e2edf002e"
  name = "k8s.io/kubernetes"

[[constraint]]
  revision = "66066c83e385e385ccc3c964b44fd7dcd413d0ed"
  name = "k8s.io/utils"

# These versions are constrained transitively by bazelbuild/rules.go

[[constraint]]
  # version = "1.1.0"
  revision = "b4deda0973fb4c70b50d226b1af49f3da59f5265"
  name = "github.com/golang/protobuf"

[[constraint]]
  revision = ""
  name = "golang.org/x/net"

[[constraint]]
  # mirror https://github.com/grpc/grpc-go
  # version = "1.10.3" // grpc-gateway
  # version = "1.7.5" // kubernetes
  revision = "5b3c4e850e90a4cf6a20ebd46c8b32a0a3afcb9e"
  name = "google.golang.org/grpc"

[[constraint]]
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"
  name = "github.com/golang/glog"

[[override]]
  # revision = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"
  name = "golang.org/x/text"